name: Bug Report
description: Create a report to help us improve.
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: |
        Please check that you have done the following things before submitting an issue.
      options:
        - label: I confirm that I have [searched for existing issues / pull requests](https://github.com/Xujiayao/MC-Discord-Chat/issues?q=) before reporting to avoid duplicate reporting.
          required: true
        - label: I confirm that I followed the [MCDC Docs](https://blog.xujiayao.top/posts/4ba0a17a/) and read the [Changelog](https://github.com/Xujiayao/MC-Discord-Chat/releases/latest), but this problem still exists.
          required: true
        - label: I confirm that I noted that if I don't follow the instructions, the issue may be closed directly.
          required: true
  - type: dropdown
    id: minecraft_version
    attributes:
      label: Minecraft Version
      description: |
        The version of Minecraft you are using?
      multiple: false
      options:
        - "1.20.2"
        - "1.20.1"
        - "1.20"
        - "1.19.4"
        - "1.19.3"
        - "1.19.2"
        - "1.19.1"
        - "1.19"
        - "1.18.2"
        - "1.18.1"
        - "1.18"
        - "1.17.1"
        - "1.17"
        - "1.16.5"
        - "1.16.4"
        - "1.16.3"
        - "1.16.2"
        - "1.16.1"
        - "1.16"
        - "1.15.2"
        - "1.15.1"
        - "1.15"
        - "1.14.4"
        - "1.14.3"
        - "1.14.2"
        - "1.14.1"
        - "1.14"
    validations:
      required: true
  - type: dropdown
    id: mcdiscordchat_version
    attributes:
      label: MC-Discord-Chat Version
      description: |
        The version of MC-Discord-Chat you are using?
      multiple: false
      options:
        - "Latest Build"
        - "2.2.3"
        - "2.2.2"
        - "2.2.1"
        - "2.2.0"
        - "1.20-2.1.4"
        - "2.1.4"
        - "2.1.3"
        - "1.19.3-2.1.2"
        - "1.19.2-2.1.2"
        - "2.1.1"
        - "2.1.0"
        - "2.0.0"
        - "2.0.0-rc.1"
        - "2.0.0-alpha.10"
        - "2.0.0-alpha.9"
        - "2.0.0-alpha.8"
        - "2.0.0-alpha.7"
        - "2.0.0-alpha.6"
        - "2.0.0-alpha.5"
        - "2.0.0-alpha.4"
        - "2.0.0-alpha.3"
        - "2.0.0-alpha.2"
        - "2.0.0-alpha.1"
        - "1.12.1"
        - "1.12.0"
        - "1.11.4"
        - "1.11.3"
        - "1.11.2"
        - "1.11.1"
        - "1.11.0"
        - "1.10.10"
        - "1.10.9"
        - "1.10.8"
        - "1.10.7"
        - "1.10.6"
        - "1.10.5"
        - "1.10.4"
        - "1.10.3"
        - "1.10.2"
        - "1.10.1"
        - "1.10.0"
        - "1.9.3"
        - "1.9.2"
        - "1.9.1"
        - "1.9.0"
        - "1.8.0"
        - "1.7.0"
        - "1.6.0"
        - "1.5.3"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please tell us what the bug is with a clear and detailed description, add screenshots to help explain.
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
      description: |
        Please provide your FULL log (/log/latest.log file) here.
      render: text
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Config
      description: |
        Please provide your FULL MC-Discord-Chat config (/config/mcdiscordchat.json file) here. Remember to REDACT the botToken!
      render: json
    validations:
      required: true
